name: Deploy React Publisher App

on:
  push:
    branches:
      - main
    paths:
      - 'publisher_app/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install and Build
        run: |
          cd publisher_app
          npm install
          npm run build

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "lwa-eh-publisher-1"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PUBLISH_APP }}
          package: "publisher_app/build"
