name: Deploy React Subscriber App

on:
  push:
    branches:
      - main
    paths:
      - 'subscriber_app/frontend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install and Build
        run: |
          cd subscriber_app/frontend
          npm install
          npm run build

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEB_APP_SUBSCRIBE_APP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_SUBSCRIBE_APP }}
          package: "subscriber_app/frontend/build"
